
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author vedantmahajan
 */
public class cashierlogin extends javax.swing.JFrame {

    /**
     * Creates new form cashierlogin
     */
    public cashierlogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf_cashier_username = new javax.swing.JTextField();
        tf_cashier_pass = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("CASHIER LOGIN");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(120, 30, 170, 30);

        jLabel2.setText("USERNAME :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 100, 76, 16);

        jLabel3.setText("PASSWORD : ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 170, 110, 16);
        getContentPane().add(tf_cashier_username);
        tf_cashier_username.setBounds(220, 100, 130, 26);

        tf_cashier_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_cashier_passActionPerformed(evt);
            }
        });
        getContentPane().add(tf_cashier_pass);
        tf_cashier_pass.setBounds(220, 160, 130, 26);

        jButton1.setText("LOGIN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(120, 240, 84, 29);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_cashier_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_cashier_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_cashier_passActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        ResultSet resultset_obj = DBLoader.executeQuery("select * from cashier where Username='"+ tf_cashier_username.getText() +"' and Password='"+ tf_cashier_pass.getText() +"'");
        
        try
        {
            if(resultset_obj.next())
            {
                JOptionPane.showMessageDialog(rootPane, "Login Successful");
            }
            
            else
            {
                JOptionPane.showMessageDialog(rootPane, "Login Failed");
            }
        } 
        catch (SQLException ex) 
        {
            Logger.getLogger(cashierlogin.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cashierlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cashierlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cashierlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cashierlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cashierlogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField tf_cashier_pass;
    private javax.swing.JTextField tf_cashier_username;
    // End of variables declaration//GEN-END:variables
}
