
import java.io.File;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author vedantmahajan
 */
public class cashier extends javax.swing.JFrame {

    /**
     * Creates new form cashier
     */
    
     ArrayList<cashierinfo> cashierList = new ArrayList<>();
     
     cashiertablemodel cashiertablemodel_obj;
    
    public cashier() {
        initComponents();
     
        cashiertablemodel_obj = new cashiertablemodel();
        
        jTable1.setModel(cashiertablemodel_obj);
        
        getcashier();
    }
    
     
    public void getcashier()
    {
        ResultSet resultset_obj = DBLoader.executeQuery("select * from cashier");
        
         try {
             while(resultset_obj.next())
             {
                cashierList.add(new cashierinfo(resultset_obj.getInt("CID") , resultset_obj.getString("Username"), resultset_obj.getString("Password")));
                
                jTable1.setRowHeight(100);
                
                cashiertablemodel_obj.fireTableDataChanged();
                
             }
         } 
         
         catch (SQLException ex) {
             Logger.getLogger(cashier.class.getName()).log(Level.SEVERE, null, ex);
         }
         
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tf_cashier_username = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tf_cashier_pass = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("NEW CASHIER");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 30, 170, 50);

        jLabel2.setText("USERNAME :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 110, 110, 16);

        tf_cashier_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_cashier_usernameActionPerformed(evt);
            }
        });
        getContentPane().add(tf_cashier_username);
        tf_cashier_username.setBounds(160, 100, 90, 26);

        jLabel3.setText("PASSWORD :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 190, 100, 16);

        tf_cashier_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_cashier_passActionPerformed(evt);
            }
        });
        getContentPane().add(tf_cashier_pass);
        tf_cashier_pass.setBounds(160, 180, 90, 26);

        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(80, 260, 75, 29);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(460, 50, 360, 340);

        jButton2.setText("DELETE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(620, 420, 90, 29);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_cashier_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_cashier_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_cashier_usernameActionPerformed

    private void tf_cashier_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_cashier_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_cashier_passActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
          if((tf_cashier_username.getText() == null)  ||  (tf_cashier_pass.getText() == null))
        {
            JOptionPane.showMessageDialog(rootPane, "ALL FIELDS ARE NECESSARY !");
        }
        else
        {
         
            try
            {
            ResultSet resultset_obj = DBLoader.executeQuery("select * from cashier where Username='"+tf_cashier_username.getText()+"'");
            
            if(resultset_obj.next())
            {
                
                JOptionPane.showMessageDialog(rootPane, "Cashier already exists");
                
            }
            else
            {
                
                resultset_obj.moveToInsertRow();
                
                resultset_obj.updateString("Username", tf_cashier_username.getText());
                
                resultset_obj.updateString("Password", tf_cashier_pass.getText());
                
                resultset_obj.insertRow();
                
                JOptionPane.showMessageDialog(rootPane, "DATA ENTRY SUCCESSFUL !");
                
            }
            
            cashierList.clear();
//            
            getcashier();
            
            
            }
            catch(Exception e)
            {
                e.printStackTrace();
            }
            
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
         
        int rowselected = jTable1.getSelectedRow();
        
        if(rowselected < 0)
        {
            JOptionPane.showMessageDialog(rootPane, "No Row Selected !");
        }
        else
        {
            String nameselected = cashierList.get(rowselected).cashier_username;
            
            ResultSet resultset_obj = DBLoader.executeQuery("select * from cashier where Username='"+ nameselected +"'");
            
            try 
            {
                resultset_obj.next();
                
                resultset_obj.deleteRow();
            } 
            catch (SQLException ex) 
            {
                Logger.getLogger(cashier.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            cashierList.clear();
            
            getcashier();
        }
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    
      class cashiertablemodel extends AbstractTableModel
    { 
          
        @Override
        public int getRowCount()
        {
            return cashierList.size();
        }
        
        @Override
        public int getColumnCount()
        {
            return 3;
        }
        
        @Override
        public Object getValueAt(int i, int j)
        {
            cashierinfo catgoryinfo_object = cashierList.get(i);
             
             if(j==0)
                 return catgoryinfo_object.CID;
             
             else if(j==1)
                 return catgoryinfo_object.cashier_username;
             
             else if(j==2)
                 return catgoryinfo_object.cashier_password;
             
             return null;
             
        }
        
        @Override
        public String getColumnName(int j)
        {
           String col[]={"CID","Username","Password"}; 
           
           return col[j];
        }
        
        
    }    
    
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new cashier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField tf_cashier_pass;
    private javax.swing.JTextField tf_cashier_username;
    // End of variables declaration//GEN-END:variables
}
