
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import sun.security.util.Password;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author vedantmahajan
 */
public class changepass extends javax.swing.JFrame {

    String global_username;
    
    /**
     * Creates new form changepass
     */
    public changepass(String global_username) {
        initComponents();
        
        this.global_username = this.global_username;
        
        setSize(500,500);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lb_username_changepass = new javax.swing.JTextField();
        lb_oldpass = new javax.swing.JTextField();
        lb_newpass = new javax.swing.JTextField();
        lb_confirmpass = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setText("USERNAME :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 40, 110, 16);

        jLabel3.setText("OLD PASSWORD :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 100, 130, 16);

        jLabel4.setText("NEW PASSWORD :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 160, 120, 16);

        jLabel5.setText("CONFIRM PASSWORD :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 210, 160, 16);

        lb_username_changepass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lb_username_changepassActionPerformed(evt);
            }
        });
        getContentPane().add(lb_username_changepass);
        lb_username_changepass.setBounds(230, 40, 110, 26);

        lb_oldpass.setText("jTextField2");
        lb_oldpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lb_oldpassActionPerformed(evt);
            }
        });
        getContentPane().add(lb_oldpass);
        lb_oldpass.setBounds(230, 90, 80, 26);

        lb_newpass.setText("jTextField3");
        getContentPane().add(lb_newpass);
        lb_newpass.setBounds(230, 150, 80, 26);

        lb_confirmpass.setText("jTextField4");
        getContentPane().add(lb_confirmpass);
        lb_confirmpass.setBounds(230, 210, 80, 26);

        jButton1.setText("CONFIRM");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(130, 260, 103, 29);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lb_username_changepassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lb_username_changepassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lb_username_changepassActionPerformed

    private void lb_oldpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lb_oldpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lb_oldpassActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        
        
        if((lb_confirmpass.getText()).equals(lb_newpass.getText()) == false)
        {
            JOptionPane.showMessageDialog(rootPane, "RE-CHECK PASSWORD !");
        }
       
        else if ((lb_newpass.getText()).equals(null) || (lb_oldpass.getText()).equals(null) || (lb_confirmpass.getText()).equals(null))
        {
            JOptionPane.showMessageDialog(rootPane, "ALL FIELDS ARE NECESSARY !");
        }
        
        ResultSet resultset_obj = DBLoader.executeQuery("select * from adminlogin where USERNAME = '" + (lb_username_changepass.getText()) +"' and PASSWORD = '" + (lb_oldpass.getText()) +"'");
        
        try {
            if(resultset_obj.next())
            {
              resultset_obj.updateString("PASSWORD", lb_confirmpass.getText());
              
              resultset_obj.updateRow();
              
              JOptionPane.showMessageDialog(rootPane, "PASSWORD CHANGED !");
            }
        } 
        catch (SQLException ex) 
        {
            Logger.getLogger(changepass.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(changepass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(changepass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(changepass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(changepass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new changepass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField lb_confirmpass;
    private javax.swing.JTextField lb_newpass;
    private javax.swing.JTextField lb_oldpass;
    public javax.swing.JTextField lb_username_changepass;
    // End of variables declaration//GEN-END:variables
}
