
import java.io.File;
import java.sql.ResultSet;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author vedantmahajan
 */
public class updateproduct extends javax.swing.JFrame {

    /**
     * Creates new form updateproduct
     */
    String pid, name, desc, bar, photo, price;

    public updateproduct(String pid, String name, String desc, String bar, String photo, String price) {
        initComponents();

        this.pid = pid;

        this.name = name;

        this.desc = desc;

        this.bar = bar;

        this.photo = photo;

        this.price = price;

        tf_update_pid.setText(pid);

        tf_update_name.setText(name);

        ta_update_desc.setText(desc);

        tf_update_barcode.setText(bar);

        lb_update_photo_path.setText(photo);

        tf_update_price.setText(price);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tf_update_pid = new javax.swing.JTextField();
        tf_update_name = new javax.swing.JTextField();
        tf_update_barcode = new javax.swing.JTextField();
        lb_update_photo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_update_desc = new javax.swing.JTextArea();
        tf_update_price = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lb_update_photo_path = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("PID");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 40, 21, 16);

        jLabel2.setText("NAME");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 110, 37, 16);

        jLabel3.setText("DESCRIPTION");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 170, 130, 16);

        jLabel4.setText("BARCODE");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 260, 60, 16);

        jLabel5.setText("PHOTO");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 320, 60, 16);

        jLabel6.setText("PRICE");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 490, 35, 16);
        getContentPane().add(tf_update_pid);
        tf_update_pid.setBounds(220, 30, 260, 26);
        getContentPane().add(tf_update_name);
        tf_update_name.setBounds(220, 100, 260, 26);
        getContentPane().add(tf_update_barcode);
        tf_update_barcode.setBounds(220, 250, 260, 26);

        lb_update_photo.setText("jLabel7");
        getContentPane().add(lb_update_photo);
        lb_update_photo.setBounds(220, 300, 200, 110);

        ta_update_desc.setColumns(20);
        ta_update_desc.setRows(5);
        jScrollPane1.setViewportView(ta_update_desc);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(220, 140, 260, 100);

        tf_update_price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_update_priceActionPerformed(evt);
            }
        });
        getContentPane().add(tf_update_price);
        tf_update_price.setBounds(220, 490, 260, 26);

        jButton1.setText("BROWSE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(460, 350, 94, 29);

        jButton2.setText("SAVE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(180, 540, 75, 29);

        lb_update_photo_path.setText("jLabel7");
        getContentPane().add(lb_update_photo_path);
        lb_update_photo_path.setBounds(220, 450, 520, 16);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_update_priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_update_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_update_priceActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        if ((tf_update_name.getText() == null) || (ta_update_desc.getText() == null)) {
            JOptionPane.showMessageDialog(rootPane, "ALL FIELDS ARE NECESSARY !");
        } else {
            String newfilename = new Date().getTime() + ".jpg";

            File file_obj1 = new File(lb_update_photo_path.getText());  //doubt 1

            new savefileinfolder(file_obj1, newfilename);

            try {

                ResultSet resultset_obj = DBLoader.executeQuery("select * from product where PID='" + pid + "'");

                //resultset_obj.moveToCurrentRow();
                if (resultset_obj.next()) {

                    resultset_obj.updateString("Name", tf_update_name.getText());

                    resultset_obj.updateString("Description", ta_update_desc.getText());

                    resultset_obj.updateString("Barcode", tf_update_barcode.getText());

                    resultset_obj.updateString("Price", tf_update_price.getText());

                    resultset_obj.updateString("Photo", "src/pics/" + newfilename);

                    resultset_obj.updateRow();

                    JOptionPane.showMessageDialog(rootPane, "DATA UPDATE SUCCESSFUL !");

                }

            } catch (Exception e) {
                e.printStackTrace();
            }

        }


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        JFileChooser jfc = new JFileChooser();

        int ans = jfc.showOpenDialog(this);

        if (ans == JFileChooser.APPROVE_OPTION) {
            File file_obj = jfc.getSelectedFile();

            lb_update_photo.setIcon(new ImageIcon(file_obj.getPath()));

            lb_update_photo_path.setText(file_obj.getPath());

        } else {
            JOptionPane.showMessageDialog(rootPane, "you need to select a file to move further");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updateproduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updateproduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updateproduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updateproduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // new updateproduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_update_photo;
    private javax.swing.JLabel lb_update_photo_path;
    private javax.swing.JTextArea ta_update_desc;
    private javax.swing.JTextField tf_update_barcode;
    private javax.swing.JTextField tf_update_name;
    private javax.swing.JTextField tf_update_pid;
    private javax.swing.JTextField tf_update_price;
    // End of variables declaration//GEN-END:variables
}
